/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package vendingmachine;

public class App {

    public static void main(String[] args) {

		String dbPath = "VM.db";
		JDBC jdbc = new JDBC(dbPath);
		// jdbc.initDB();

		Model model = new Model(jdbc);
		DefaultPageView defaultPageView = new DefaultPageView();
		Controller controller = new Controller(model, defaultPageView);
		defaultPageView.setController(controller);
		defaultPageView.setModel(model);

// ######################
// ### Testing Starts ###
// ######################




// ####################
// ### Testing Ends ###
// ####################

		controller.launchWindow();
		controller.updateView();

    }
}
