/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package vendingmachine;

public class App {

    public static void main(String[] args) {

		String dbPath = "VM.db";
		JDBC jdbc = new JDBC(dbPath);

		Model model = new Model(jdbc);	
		DefaultPageView defaultPageView = new DefaultPageView(model);
		Controller controller = new Controller(model, defaultPageView);

// ######################
// ### Testing Starts ###
// ######################
		model.setCurrentUser(jdbc.getUser("Dahao"));
		System.out.println("Testing init done");
// ####################
// ### Testing Ends ###
// ####################

		controller.ViewUpdate();

    }
}
